### PR TITLE
rewrite write handler without using obv

### PR DESCRIPTION
**Pull request by dominictarr**
different approach that is simpler and avoids the weirdness around removing listeners to an observable

### CODE REVIEW

**Review by christianbundy — APPROVED** [review]
LGTM, should we publish as 1.2.0?

**Comment by dominictarr** [comment]
@christianbundy go ahead!

**Comment by christianbundy** [comment]
Oops, could you `npm publish` or add me to the npm org?

**Comment by dominictarr** [comment]
there wasn't an npm org, so I created one and added you and all the modules to it.

**Pull request merged**
